authentication
GSG-G13/fluentoo pull request #13
Opened 2023-06-13 17:58 UTC by AyaQunoo

2023-06-13 19:30 UTC, devstm requested changes

2023-06-13 19:30 UTC, devstm commented on server/database/config/connection.js
> +sequelize.sync();
recommit this line or try to but in in if() body based on NODE_ENV variable

2023-06-13 19:30 UTC, devstm commented on server/routes/index.js
>  router.use('/lang', languageRouter);
i know its not your change but lang is not descriptive name for this router
sorry :(

2023-06-13 19:30 UTC, devstm commented on server/__test__/test.js
> +/* eslint-disable no-console */
Try to test the end-points in two scenarios for each end-point

2023-06-13 19:30 UTC, devstm commented on server/controllers/User/login.js
> +      return res.json('password incorrect');
throw unAuth Error :1st_place_medal:

2023-06-13 19:30 UTC, devstm commented on server/controllers/User/login.js
> +const { CustomeError } = require('../../utils/helper/customeError');
use the index.js in utils insted of ../../utils/validation/user

2023-06-13 19:30 UTC, devstm commented on server/controllers/User/login.js
> +const User = require('../../models/user');
create index file in models folder

2023-06-13 19:30 UTC, devstm commented on server/controllers/User/oauth.js
> +      // eslint-disable-next-line no-unused-vars
if you use error first approach you dont need 
      // eslint-disable-next-line no-unused-vars
      anymore

2023-06-13 19:30 UTC, devstm commented on server/controllers/User/oauth.js
> +      id: existingUser.id,
if there is no existingUser its shoud take the new user was created so try to handle that

2023-06-13 19:30 UTC, devstm commented on server/controllers/User/oauth.js
> +        msg: 'authenticated sucssfully',
return the user data

2023-06-13 19:30 UTC, devstm commented on server/controllers/User/oauth.js
> +    return res.status(401).json({ message: 'Authentication failed' });
return status

2023-06-14 13:21 UTC, MohammedMahani approved these changes

2023-06-14 13:25 UTC, abdullah-alsharif approved these changes

2023-06-14 13:44 UTC, Basel-01 approved these changes

2023-06-14 13:45 UTC, merged