feat: landing page components
GSG-G13/fluentoo pull request #25
Opened 2023-06-17 15:04 UTC by MohammedMahani

2023-06-22 14:32 UTC, abdullah-alsharif commented on client/src/App.tsx
> +    element: <LandingPage/ >,
you can use home or anything else for this router 
Landingpage is tall and not common

2023-06-22 14:35 UTC, adalah-sh commented on client/src/components/LandingPage/Feature.tsx
> +{/* <div className="feat-sec">
remove the comment

2023-06-23 11:52 UTC, devstm requested changes

2023-06-23 11:52 UTC, devstm commented on client/src/components/LandingPage/AboutUs.tsx
> +              {' '}
what is all in one and why you need me to merge this 'Lorem, ipsum' in main branch?

2023-06-23 11:52 UTC, devstm commented on client/src/components/LandingPage/AboutUs.tsx
> +          <Card className='gg'>
what is card content ?

2023-06-23 11:52 UTC, devstm commented on client/src/components/LandingPage/AboutUs.tsx
> +        <Col span={8}>
dont repeat the code use array.map and split the code into new cmponents

2023-06-23 11:52 UTC, devstm commented on client/src/components/LandingPage/Feature.tsx
> +          Lorem, ipsum dolor sit amet consectetur adipisicing elit. Dignissimos,
Be more creative in choosing words

2023-06-23 11:52 UTC, devstm commented on client/src/components/LandingPage/Feature.tsx
> +          <Image
each image should has alt and fallback attributes

2023-06-23 11:52 UTC, devstm commented on client/src/components/LandingPage/Feature.tsx
> +      <Row className='feat-container'>
I think this code is repeated more than once

2023-06-23 11:52 UTC, devstm commented on client/src/components/LandingPage/Hero.tsx
> +      <Row gutter={[8, 8]} style={{ marginRight: 0 }}>
we use inline stile just for test not to merge it into the main so dont push any inline stilyle on Github

2023-06-23 11:52 UTC, devstm commented on client/src/components/LandingPage/LandingPage.css
rename this file to style.module.css

2023-06-23 11:52 UTC, devstm commented on client/src/components/common/Footer.tsx
Is that all the footer will contain?
I looked at the figma and I think this component is very small compared to the size of the footer there -in figma-

2023-06-23 11:52 UTC, devstm commented on client/src/components/common/NavBar.tsx
> +          <Menu mode="horizontal" defaultSelectedKeys={['1']} style={{ background: 'none', display: 'flex', alignItems: 'center' }}>
inline style

2023-06-24 23:38 UTC, closed without merging