build: card component
GSG-G13/fluentoo pull request #26
Opened 2023-06-17 15:54 UTC by AyaQunoo

2023-06-18 06:55 UTC, devstm requested changes

2023-06-18 06:55 UTC, devstm commented on client/src/components/Card/card.tsx
> +        <img src='https://th.bing.com/th/id/OIP.f3DM2upCo-p_NPRwBAwbKQHaHa?pid=ImgDet&rs=1' style={{width:70 , height:70}}/>
Antd Image Component

2023-06-18 06:55 UTC, devstm commented on client/src/components/Card/card.tsx
> +    <Card style={{ width: 300 }}>
dont use inline style

2023-06-18 06:55 UTC, devstm commented on client/src/components/Card/card.tsx
> +function CardDiv() {
CardDiv is not descriptive name for this component

2023-06-18 06:55 UTC, devstm commented on client/src/components/Card/card.tsx
> +       <h2>Aya Qunoo</h2>
this name recived from component props

2023-06-18 06:55 UTC, devstm commented on client/src/components/Card/card.tsx
> +        <img src="https://cdn-icons-png.flaticon.com/128/206/206657.png" alt="" />
Use antd Image Component

2023-06-18 06:57 UTC, devstm requested changes

2023-06-18 06:57 UTC, devstm commented on client/src/components/Card/card.tsx
> +import React from 'react'
this file name should  be index.tsx

2023-06-18 06:57 UTC, devstm commented on client/src/components/Card/Card.modules.css
> +.css-dev-only-do-not-override-12jzuas.ant-btn-dashed:hover {
style.module.css

2023-06-18 06:57 UTC, devstm commented on client/src/pages/Community/community.modules.css
> +.community {
style.module.css

2023-06-22 15:01 UTC, adalah-sh commented on client/src/pages/Community/index.tsx
> +import { Button, Dropdown,  Space } from 'antd';
merge between line 2 and 3

2023-06-22 15:04 UTC, adalah-sh commented on client/src/pages/Community/index.tsx
> +import menuItems from './menuItems';
maybe u can use menuItems as component is better

2023-06-22 15:06 UTC, adalah-sh commented on client/src/components/Card/card.tsx
> +       <img src="https://cdn-icons-png.flaticon.com/128/555/555613.png" alt="" /></div>
let the img component be changeable (use props for example)

2023-06-25 07:28 UTC, MohammedMahani commented on client/src/App.tsx
> +import Community from './pages/Community';
we have index.js in (pages) folder > so you should import it from ( ./pages )

2023-06-28 20:39 UTC, closed without merging