build: chat fronend
GSG-G13/fluentoo pull request #29
Opened 2023-06-18 12:05 UTC by AyaQunoo

2023-06-18 12:10 UTC, Basel-01 approved these changes

2023-06-21 15:22 UTC, devstm requested changes

2023-06-21 15:22 UTC, devstm commented on client/src/components/ChatBox/index.tsx
> +import axios from 'axios';
axios is 3rd party module should be on the top

2023-06-21 15:22 UTC, devstm commented on client/src/components/ChatBox/index.tsx
> +  const makeArrayOfObjectsUnique = (arr: UserObjectType[]) => {
define this function in on onther file 
utils/services

2023-06-21 15:22 UTC, devstm commented on client/src/components/ChatBox/index.tsx
> +  }, [selectedUser.userId]);
selectedUser not selectedUser.userId

2023-06-21 15:22 UTC, devstm commented on client/src/components/ChatUserHead/index.tsx
> +        src='https://th.bing.com/th/id/OIP.f3DM2upCo-p_NPRwBAwbKQHaHa?pid=ImgDet&rs=1'
use user image and this link should be in dalback api attrbute

2023-06-21 15:23 UTC, adalah-sh approved these changes

2023-06-22 06:57 UTC, devstm approved these changes

2023-06-22 06:58 UTC, MohammedMahani approved these changes

2023-06-22 06:59 UTC, merged