Create server
GSG-G13/fluentoo pull request #3
Opened 2023-06-08 12:02 UTC by AyaQunoo

[](https://stm1998.atlassian.net/browse/LW-3?atlOrigin=eyJpIjoiZDY1ZDdjMmE5NDIwNDMzM2IyNjU2MDViMjUwYWNhN2EiLCJwIjoiaiJ9)

2023-06-08 12:03 UTC, MohammedMahani approved these changes

2023-06-08 12:04 UTC, Basel-01 approved these changes

2023-06-08 16:58 UTC, adalah-sh approved these changes

2023-06-09 12:48 UTC, devstm requested changes

2023-06-09 12:48 UTC, devstm commented on package.json
> +    "start": "node server",
I think the environment should be taken into consideration
(dev, test, production)

2023-06-11 06:52 UTC, devstm approved these changes

2023-06-11 06:52 UTC, merged