fix: refactor backend code
GSG-G13/fluentoo pull request #40
Opened 2023-06-22 14:28 UTC by adalah-sh

Add:
-  server/config/
-  server/database/connection.js
-  server/database/faker/
-  server/database/schema/
-  server/database/seed/
- morgan package

Modified:
- package-lock.json
- package.json
- server/app.js
- server/models/feedBack.js
- server/models/index.js
- server/models/language.js
- server/models/message.js
- server/models/profile.js
- server/models/user.js

Deleted:
- server/database/.gitkeep
- server/database/config/build.sql
- server/database/config/connection.js

2023-06-24 22:39 UTC, devstm approved these changes

2023-06-24 23:40 UTC, MohammedMahani approved these changes

2023-06-25 00:02 UTC, Basel-01 requested changes

2023-06-25 00:02 UTC, Basel-01 commented on server/app.js
> +const appConfig = require('./config/app.config');
you already have index.js file in config folder that exports appConfig object

2023-06-25 00:02 UTC, Basel-01 commented on server/config/index.js
> +};
I think it will better to export googleConfig as object instead of exporting googleId and googleSecret.
like you did already in databaseConfig and appConfig.

2023-06-25 00:02 UTC, Basel-01 commented on server/database/connection.js
> +} = require('../config');
in database.config.js file you export hostname but here you import it as host.
you need to edit it to be like this databaseConfig: { ..., hostname, ... }

2023-06-25 00:02 UTC, Basel-01 commented on package.json
> +    "db:seed": "node server/database/seed/index.js"
db:seed will work without /index.js

2023-06-25 07:51 UTC, Basel-01 approved these changes

2023-06-25 07:51 UTC, merged