fix: test in github
GSG-G13/fluentoo pull request #44
Opened 2023-06-25 08:17 UTC by adalah-sh

2023-06-25 17:19 UTC, ahmedmurtaja approved these changes

2023-07-01 08:12 UTC, devstm requested changes

2023-07-01 08:12 UTC, devstm commented on server/controllers/Profile/getProfile.js
> +    if (profileId && Number.isNaN(+profileId)) throw new CustomeError('"profileId" must be a number', 400);
what is this do?

2023-07-01 16:41 UTC, devstm approved these changes

2023-07-01 16:42 UTC, merged