Chat features
GSG-G13/fluentoo pull request #45
Opened 2023-06-25 09:43 UTC by MohammedMahani

2023-06-25 13:07 UTC, devstm requested changes

2023-06-25 13:07 UTC, devstm commented on client/package.json
> +    "url": "^0.11.1",
uneeded backage

2023-06-25 13:07 UTC, devstm commented on client/src/components/ChatBox/style.modules.css
> +    /* justify-content: space-between; */
dilete line or uncoment

2023-06-25 13:07 UTC, devstm commented on client/src/components/Message/index.tsx
> +  const countries = {
put this opject in new file

2023-06-25 13:07 UTC, devstm commented on server/controllers/errors/serverError.js
> +  console.log(err);
remove this console

2023-06-25 13:07 UTC, devstm commented on server/config/app.config.js
> +  port: 5000,
undo this change

2023-06-25 13:07 UTC, devstm commented on package.json
> +    "google-tts-api": "^2.0.2",
is it needed

2023-06-27 14:58 UTC, AyaQunoo commented on client/src/components/Message/index.tsx
> +      if(translate){
no need for if statment you can setTranslate(!translate);

2023-07-01 08:26 UTC, devstm approved these changes

2023-07-01 08:26 UTC, devstm commented on client/src/components/Message/index.tsx
> +import { Select,Collapse, Alert } from 'antd';
antd should be in top of utils

2023-07-01 16:11 UTC, adalah-sh approved these changes

2023-07-01 16:11 UTC, abdullah-alsharif commented on server/controllers/errors/serverError.js
> +  console.log(err);
remove console.log here

2023-07-02 16:44 UTC, devstm approved these changes

2023-07-02 16:44 UTC, merged