build: card & menu components
GSG-G13/fluentoo pull request #46
Opened 2023-06-28 20:38 UTC by AyaQunoo

2023-07-01 08:23 UTC, devstm requested changes

2023-07-01 08:23 UTC, devstm commented on client/src/components/DropDownMenu/menuItems.ts
> +  icon:' ll'
![image](https://github.com/GSG-G13/fluentoo/assets/54906217/e85a8ec3-fb27-4f2b-8cf0-6e7d4410d30c)

2023-07-01 08:23 UTC, devstm commented on client/src/components/DropDownMenu/menuItems.ts
> +  icon:' ll'
icon ll !!!!!!!!!!!!!!1

2023-07-01 16:23 UTC, adalah-sh commented on client/src/pages/Community/index.tsx
> +import Menu from '../../components/DropDownMenu';
merge line 4 and 5

2023-07-01 16:37 UTC, adalah-sh commented on client/src/pages/Community/index.tsx
spokenLanguages and practiceLanguages must be an array not string

2023-07-04 11:49 UTC, adalah-sh approved these changes

2023-07-04 17:48 UTC, devstm approved these changes

2023-07-04 17:48 UTC, merged