build: sending emails
GSG-G13/fluentoo pull request #56
Opened 2023-07-07 16:16 UTC by AyaQunoo

2023-07-07 19:45 UTC, devstm requested changes

2023-07-07 19:45 UTC, devstm commented on server/utils/email/nodemailer.js
> +const user = process.env.USER;
use app.config or mail.config 
const user = process.env.USER;

2023-07-07 19:45 UTC, devstm commented on server/utils/email/nodemailer.js
> +      user,
not descripteve names

2023-07-07 19:45 UTC, devstm commented on server/utils/email/nodemailer.js
> +    from: user,
from: "noreplay@fluento.ps"

2023-07-07 20:42 UTC, devstm approved these changes

2023-07-10 10:53 UTC, adalah-sh approved these changes
solve Conflict

2023-07-10 13:24 UTC, merged